baseURL = 'https://www.arjunuvacha.com/'
languageCode = 'en-us'
title = 'Arjun Uvacha'
theme = 'hugo-theme-stack'


DefaultContentLanguage = "en"
hasCJKLanguage = false

[languages.en]
languageName = "English"
title = "Arjun Uvacha"
description = "🔍 a product manager's perspective of everyday things."
weight = 1

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "au.png"
rssFullContent = true
favicon = "favicon.png"

[params.footer]
since = 2020

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[params.sidebar]
compact = false
emoji = "✏️"
subtitle = "🔍 a product manager's perspective of everyday things."

[params.sidebar.avatar]
enabled = true
local = true
src = "img/au.png"

[params.article]
math = false
toc = true
readingTime = true

[params.article.license]
enabled = false

[params.comments]
enabled = true
provider = "remark42"
noComment = false

[params.comments.disqusjs]
shortname = "arjunuvacha"

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]
    host = "https://arjunuvacha-3de80-default-rtdb.firebaseio.com/"
    site = "remark"
    locale = "en"

    [params.comments.vssue]
    autoCreateIssue = false

    [params.comments.waline]
    emoji = [ "https://unpkg.com/@waline/emojis@1.0.1/weibo" ]
    requiredMeta = [ "name", "email", "url" ]

      [params.comments.waline.locale]
      admin = "Admin"

    [params.comments.twikoo]

    [params.comments.cactus]
    defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
    serverName = "cactus.chat"
    siteName = ""

    [params.comments.giscus]
    reactionsEnabled = 1
    emitMetadata = 0

    [params.comments.gitalk]

    [params.comments.cusdis]
    host = "https://arjunuvacha.com"
    id ="ac4ac4e3-ee84-4182-8b19-7ad6edca09b9"

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

  [params.widgets.homepage.params]
  limit = 5

[[params.widgets.homepage]]
type = "categories"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
site = "arjunuvacha_"
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = true
local = false

  [params.colorScheme]
  toggle = false
  default = "light"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
  [[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
pre = "home"

[menu.main.params]

  [[menu.social]]
    identifier = "linkedin"
    name = "Linkedin"
    url = "https://linkedin.com/in/harisharjun"

      [menu.social.params]
        icon = "brand-linkedin"

  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/arjunuvacha_"

    [menu.social.params]
      icon = "brand-twitter"

  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/harisharjun"

    [menu.social.params]
      icon = "brand-github"

  [[menu.social]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://instagram.com/arjunuvacha"

    [menu.social.params]
      icon = "brand-instagram"


[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.renderer]
unsafe = false

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4

