import type { Challenge } from './grading/types';

// Static imports so wrangler bundles the challenge data into the Worker at deploy
// time. There is no filesystem on the edge, so this is how the data gets there.
// Generated by projects/prompt-gym/build/convert.mjs — never hand-edited.
import pgA1 from '../../../projects/prompt-gym/challenges/generated/pg-a1.json';
import pgA2 from '../../../projects/prompt-gym/challenges/generated/pg-a2.json';
import pgA3 from '../../../projects/prompt-gym/challenges/generated/pg-a3.json';
import pgA11 from '../../../projects/prompt-gym/challenges/generated/pg-a11.json';
import pgB1 from '../../../projects/prompt-gym/challenges/generated/pg-b1.json';
import pgB3 from '../../../projects/prompt-gym/challenges/generated/pg-b3.json';
import pgB7 from '../../../projects/prompt-gym/challenges/generated/pg-b7.json';
import pgC1 from '../../../projects/prompt-gym/challenges/generated/pg-c1.json';
import pgC5 from '../../../projects/prompt-gym/challenges/generated/pg-c5.json';
import pgD2 from '../../../projects/prompt-gym/challenges/generated/pg-d2.json';
import pgE4 from '../../../projects/prompt-gym/challenges/generated/pg-e4.json';
import pgF1 from '../../../projects/prompt-gym/challenges/generated/pg-f1.json';

const ALL = [pgA2, pgA1, pgA3, pgA11, pgB7, pgB1, pgB3, pgC1, pgC5, pgD2, pgE4, pgF1];

/** Ordered as the catalog recommends playing them, easiest first. */
export const challenges: Challenge[] = ALL as unknown as Challenge[];

export function findChallenge(id: string): Challenge | undefined {
  return challenges.find((c) => c.id === id);
}
